services:

    sonata.admin.category:
        class: AdminBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Site", label: "Category" }
        arguments:
            - ~
            - AppBundle\Entity\Category
            - ~
        calls:
            - [ setTranslationDomain, [AdminBundle]]     
    
    sonata.admin.page:
        class: AdminBundle\Admin\PageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Site", label: "Page" }
        arguments:
            - ~
            - AppBundle\Entity\Page
            - ~
        calls:
            - [ setTranslationDomain, [AdminBundle]]         
    
    sonata.admin.menu:
        class: AdminBundle\Admin\MenuAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Site", label: "Menu" }
        arguments:
            - ~
            - AppBundle\Entity\Menu
            - ~
        calls:
            - [ setTranslationDomain, [AdminBundle]] 
    
    sonata.admin.keyword:
        class: AdminBundle\Admin\KeywordAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Site", label: "Keyword" }
        arguments:
            - ~
            - AppBundle\Entity\Keyword
            - ~
        calls:
            - [ setTranslationDomain, [AdminBundle]] 
      
    sonata.admin.pageTitle:
        class: AdminBundle\Admin\PageTitleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Site", label: "PageTitle" }
        arguments:
            - ~
            - AppBundle\Entity\PageTitle
            - ~
        calls:
            - [ setTranslationDomain, [AdminBundle]] 
            
    sonata.admin.paragraph:
        class: AdminBundle\Admin\ParagraphAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Site", label: "Paragraph" }
        arguments:
            - ~
            - AppBundle\Entity\Paragraph
            - ~
        calls:
            - [ setTranslationDomain, [AdminBundle]]         
                    
    sonata.admin.user:
        class: AdminBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Site", label: "User" }
        arguments:
            - ~
            - AppBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [AdminBundle]]                    