# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_MODERATOR: ROLE_MODERATOR
        ROLE_SUPER_ADMIN: [ROLE_ADMIN,ROLE_SONATA_ADMIN]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        admin:
            pattern: /admin(.*)
            context:  user
            form_login:
                provider: fos_userbundle
                login_path: /login
                use_forward:  false
                check_path: /admin/login_check
                default_target_path:  /admin/dashboard        
            logout:    
                 path: /admin/logout
                 target: /index
            anonymous:    true
        main:
            pattern: .*
            context:  user
            form_login:
                provider: fos_userbundle
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                use_forward:  false
                csrf_provider: form.csrf_provider
                default_target_path:  /admin/dashboard                            
            logout:    
                 path: fos_user_security_logout
                 target: /index
            anonymous:    true
           
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: [ROLE_ADMIN,ROLE_SONATA_ADMIN,ROLE_MODERATOR] }
